import type { Metadata } from "next";
import { Geist, Sarabun, Prompt } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "@/context/SessionContext";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const sarabun = Sarabun({
  variable: "--font-sarabun",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["thai"]
});
const prompt = Prompt({
  variable: "--font-prompt",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["thai"]
});

export const metadata: Metadata = {
  title: "App Template 2025 by Tanasat Sudjing",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* ใส่ script SDK ของ Google */}
        <script
          src="https://accounts.google.com/gsi/client"
          async
          defer
        ></script>
      </head>      
      <body className={`${geistSans.variable} ${sarabun.variable} ${prompt.variable} antialiased`}>
        <SessionProvider>
          {/* <TopNav/> */}
          {children}
        </SessionProvider>
        <Toaster
          toastOptions={{
            duration: 2000,
          }}
        />
      </body>
    </html>
  );
}
