import type { Metadata } from "next";
import { Geist, Sarabun ,Prompt } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "@/context/SessionContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const sarabun = Sarabun({
  variable: "--font-sarabun",
  weight:["100","200","300","400","500","600","700","800"],
  subsets:["thai"]
});
const prompt = Prompt({
  variable: "--font-prompt",
  weight:["100","200","300","400","500","600","700","800"],
  subsets:["thai"]
});

export const metadata: Metadata = {
  title: "App Template 2025 by Tanasat Sudjing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${sarabun.variable} ${prompt.variable} antialiased`}>
        <SessionProvider>
        {/* <TopNav/> */}
        {children}
        </SessionProvider>
      </body>
    </html>
  );
}
