export const Navlinks = [
    {
        id:1,
        url:"/dashboard",
        label:"Dashboard",
    },
    {
        id:2,
        url:"/product",
        label:"Product",
    },
    {
        id:3,
        url:"/feature",
        label:"Feature",
    },
    {
        id:4,
        url:"/about",
        label:"About",
    },
]