# .github/workflows/deploy.yml
name: Build Next.js and Upload Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install dependencies
      run: npm install

    - name: Build Next.js
      run: npm run build

    - name: Prepare deploy folder
      run: |
        mkdir deploy
        cp -r .next deploy/
        cp -r public deploy/
        cp package.json deploy/
        cp next.config.ts deploy/
        cp -r node_modules deploy/

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: nextjs-build
        path: ./deploy